### ISSUE TITLE
scrolling in doc is terrible

### ISSUE THREAD

**Issue by Offirmo** [Famous/famous-angular#327] opened 2015-01-27 11:02 UTC
Hello,

looking at the doc : https://famo.us/integrations/angular/#/intro

we are asked to "scroll to see it in action". However, the scroll response is terrible and I have to scroll 10 seconds to go to the next page.

Problem reproduced on both FF latest and Chrome latest.

**Comment by jordanpapaleo** [comment] 2015-01-27 22:03
Hi @Offirmo - 

Thank you for reporting this.  This is a known issue and I have also experienced it.  The issue is not with Famous-Angular but how it was implemented.  I just sent a proposal to the right people at Famo.us and hopefully it will get resolved but I cannot guarantee anything.  For now, clicking links is the best way to navigate the site if you are using a "normal" mouse that cannot detect velocity or touch events.  I am going to close this issue because it is not within the scope of this git project.  It is not an error with famous-angular; it is an error with this part of the Famo.us website that built by a third party.  We do appreciate your support of Famous-Angular.

Thank you,

Jordan

**Closed by jordanpapaleo** 2015-01-27 22:03 UTC

**Comment by zackbrown** [comment] 2015-01-28 00:31
Agreed with @jordanpapaleo — this is a bug in the application logic for the docs site, which implemented custom scrolling logic with escape velocity; that app was built specifically for a MacBook scroll pad and was not exhaustively tested on other hardware prior to release.

A better place to open this issue would be for the repo housing that app:  https://github.com/thomasstreet/famous-angular-docs .  The file containing the scroll logic is here:  https://github.com/thomasstreet/famous-angular-docs/blob/master/app/scroll-logic/scroll-handlers.js

**Comment by Offirmo** [comment] 2015-01-28 08:49
@jordanpapaleo hello, nice to hear from you ! Thanks for reporting it to famo.us, @zackbrown I will do my share and report it in famous-angular-doc
